### PR TITLE
Update UT performance data for main/PR 169

### PR DESCRIPTION
**Pull request by Sindica**
For list/watch code change performance comparison

### CODE REVIEW

**Comment by yb01** [comment]
PR #169 is changes in the perf test setup scripts, any reason it could affect perf UT results ?

**Comment by Sindica** [comment]
> PR #169 is changes in the perf test setup scripts, any reason it could affect perf UT results ?

PR 169 does not affect perf UT result. It is used as a marker. Somewhere in the history that the perf data was changed.

**Review by yb01 — APPROVED** [review]
/lgtm

**Comment by yb01** [comment]
> > PR #169 is changes in the perf test setup scripts, any reason it could affect perf UT results ?
> 
> PR 169 does not affect perf UT result. It is used as a marker. Somewhere in the history that the perf data was changed.

i see. i will be alway good to pinpoint the change that affected the perf. but if it is time consuming, we should be fine to use this PR 169 as the line.

**Pull request merged**
